---
# Source: demo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-demo
  labels:
    helm.sh/chart: demo-0.1.0
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
      app.kubernetes.io/instance: dev
  template:
    metadata:
      labels:
        helm.sh/chart: demo-0.1.0
        app.kubernetes.io/name: demo
        app.kubernetes.io/instance: dev
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: dev-demo
      containers:
        - name: demo
          image: "ghcr.io/cfi2017/kargo-demo:develop@sha256:681c29ddd767b474dd59efd6296d56f6edb164c9fb08585751137304a6d4ff0c"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
