---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-dev
  labels:
    app.kubernetes.io/name: kargo-demo-dev
    app.kubernetes.io/component: kargo-demo
    pod-security.kubernetes.io/enforce: restricted
