apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: develop
  namespace: kargo-demo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/cfi2017/kargo-demo/server
        imageSelectionStrategy: Digest
        constraint: main
    - git:
        repoURL: git@github.com:cfi2017/kargo-demo.git
        includePaths:
          - 'glob:charts/**'
          - 'glob:values/**'
        branch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: release
  namespace: kargo-demo
spec:
  subscriptions:
    - image:
        # match on semver
        repoURL: ghcr.io/cfi2017/kargo-demo/server
    - git:
        repoURL: git@github.com:cfi2017/kargo-demo.git
        commitSelectionStrategy: SemVer
  freightCreationCriteria:
    expression: |
      imageFrom('ghcr.io/cfi2017/kargo-demo/server').Tag == commitFrom('git@github.com:cfi2017/kargo-demo.git').Tag
