apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: "#0000FF"
spec:
  vars:
    - name: gitopsRepo
      value: git@github.com:cfi2017/kargo-demo.git
  requestedFreight:
    - origin:
        kind: Warehouse
        name: develop
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: srcPath
          value: ./repo/charts/demo
        - name: outPath
          value: ./repo/manifests/${{ ctx.stage }}
        - name: tmpPath
          value: ./out
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - branch: develop
                path: ./repo
        - uses: delete
          config:
            path: ${{ vars.outPath }}
        - uses: helm-template
          config:
            path: ${{ vars.srcPath }}
            outPath: ${{ vars.tmpPath }}
            outLayout: helm
            namespace: kargo-demo-${{ ctx.stage }}
            releaseName: ${{ ctx.stage }}
            setValues:
              - key: image.tag
                value: develop@${{ imageFrom("ghcr.io/cfi2017/kargo-demo/server", warehouse("develop")).Digest }}
        - uses: copy
          config:
            inPath: ${{ vars.tmpPath }}/demo/templates
            outPath: ${{ vars.outPath }}
        - uses: delete
          config:
            path: ${{ vars.tmpPath }}
        - uses: git-commit
          config:
            path: ./repo
            message: "chore(${{ ctx.stage }}): update manifests"
        - uses: git-push
          config:
            path: ./repo
